
# Etapa 1: build con Node.js
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Anula la variable de entorno CI para permitir advertencias sin fallar
ENV CI=false
ENV NODE_OPTIONS=--openssl-legacy-provider
RUN npm run build

# Etapa 2: servir estáticos con Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

# (opcional) configuración personalizada de nginx
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
